name: CI Pipeline

on:
  push:
    branches:
      - Maria_Melendez
  pull_request:
    branches:
      - Maria_Melendez

jobs:
  build-test-run:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # or the latest LTS version

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Run tests
      run: npm test

    - name: Run program
      run: npm start

    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: dist
        path: dist
